### ISSUE TITLE
Request to Remove Password Function from Wallet or Alternative Solution

### ISSUE THREAD

**Issue by tstol002** [hacash/cmdwallet#2]
More than 1 of the HacashPool community members have determined that if they enter the same password into the wallet creator UI, it will output the same private key.

See here: https://gyazo.com/5bf57dea4b1708c8bc64f1dc03bcf5c4

We need a solution to either 1) Remove the password creation option (thereby leaving users with only a private key on output) or to 2) Disassociate the way passwords always equal the same private key.

The chances of the same private key is so close to zero it is nearly non-existent. 

The chances of someone entering the same password and therefore getting access to an existing private key is much more likely.

Credit to Telegram users @keszyn and @Alex670000 for originally locating this "bug".

**Comment by jojoin** [comment]
The private key always needs to be backed up in a certain place, which is easy to be lost and stolen by hackers, and the password can be memorized in the brain.

So it's a tradeoff and alternative security, there's no absolute security.

CMDWallet also offer a pure private key solution:  

```
> newkey
> prikey
```

**Comment by tstol002** [comment]
I understand the trade off. I believe having a "convenience" solution that allows for one to access another's funds is not acceptable.

You are correct: Lost or stolen private keys is a risk. However, the probability of someone using an identical password to another individual's seems to be a far higher probability. Furthermore, such a breach is not the fault of a hacker or thief, it is a fault of the wallet UI itself and the company that hosts the wallet UI (HacashPool).

If someone misplaces their priv key or a thief breaks in to their home or a hacker connects to their computer, the victim will place blame to themselves, the thief or the hacker. If someone, by complete chance, enters the same password as another's wallet and gains access to another's funds, who do you think will be blamed? The wallet UI or HacashPool? 

If an actual hack does occur on someone's machine and they are aware of this wallet "feature", do you think they will think "I was hacked" a or do you think they will go to the more easily contactable target in which the wallet UI is hosted (HacashPool)?

Please reconsider. This is a bad design and has future "troubles" for whoever decides to host it.

**Comment by anj1nsan** [comment]
I m totally agree with tstol, this is a big security error and it need to be fixed asap (just by removing [password] option when creating wallet). 
You never can guess other people private keys, but you can easy enough guess their password. 
And - magic! - you get access to their wallets!

Yeah, password is easy to remember, but when we have deal with crypto, [safe] is more important than [comfortable].

**Comment by keszyn** [comment]
jojoin, imho if there still will be a password there will be for sure some people who will loose their HAC. If You don't wanna turn off password option - write a information that password needs to be as unique as hell, so it won't be used by noone else, instead somoone else will have extremly easy option to take Your HAC's. Usually when we loose our priv key coins are gone here we can easy restore by putting pass in to the password field like Trevor showed on the movie.

imho in this way, wallets with password's are not well secured...

**Comment by jojoin** [comment]
I accept your opinion.

Password features will be gradually removed in future node versions and will be removed from all subsequent applications.

Thank you for your advice! Let me understand that this is not safe for everyone, because not everyone has a password that is complex enough like me:)
