### ISSUE TITLE
Why Does The Private Key Output Only Use Uppercase Letters?

### ISSUE THREAD

**Issue by tstol002** [hacash/cmdwallet#3]
Title says it all.

All other wallets I have used personally always output private keys using numbers, uppercase and lowercase letters. More secure that way since there are many more combinations.

Why does the Hacash chain only user uppercase letters?

**Comment by jojoin** [comment]
Technically speaking, it is the same whether the private key is encoded in uppercase or lowercase.

So, it's just a trivial choice for hacash to always use uppercase letters.
